[package]
name = "quad"
version = "0.1.0"
authors = ["Grégory Obanos <gregory.obanos@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.5"
image = "0.19"
log = "0.4"
winit = "0.18"
glsl-to-spirv = "0.1.4"
gfx-hal = "0.1.0"
gfx-backend-vulkan = "0.1.0"